"""Sole generator. Every generated artifact in this bundle descends from grounding.yaml.

Generates solve.sh, TRUTH.md, rubrics.json, tests/test_output.py, the canonical payload of
provenance.yaml, and the checker fixtures. Phase 2 step 7 requires every one of these to
regenerate bit-identically, so this file must be a pure function of grounding.yaml plus the
corpus signatures it reads. It contains no randomness and reads no clock.
"""
from __future__ import annotations

import hashlib
import json
import os
import sys

import yaml

HERE = os.path.dirname(os.path.abspath(__file__))
BUNDLE = os.path.dirname(HERE)
GROUNDING = os.path.join(HERE, "grounding.yaml")
BANNER = "GENERATED SECTION. DO NOT HAND-EDIT."


def load():
    with open(GROUNDING) as f:
        return yaml.safe_load(f)


def _w(path, text):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", newline="\n") as f:
        f.write(text)


def gen_solve_sh(g):
    ref = g["reference_solution"]
    text = f"""#!/usr/bin/env bash
# {BANNER}
# Generated by solution/recompute.py from solution/grounding.yaml.
set -euo pipefail
cd "$(dirname "$0")/.."

# The oracle installs the reference optimizer as the submission and runs the instrumented
# harness runner for the declared seed set. It reaches full reward only if the reference
# optimizer actually attains the target loss inside the bound step count, which has not
# been demonstrated on any host to date. See gap-oracle-unexecuted-no-accelerator.
mkdir -p submission/logs
cp solution/{os.path.basename(ref['module'])} submission/optimizer.py
exec python runner/run_track3.py --seeds 0,1 --max-steps {g['reward_schema']['baseline_steps']}
"""
    _w(os.path.join(BUNDLE, "solution", "solve.sh"), text)
    os.chmod(os.path.join(BUNDLE, "solution", "solve.sh"), 0o755)


def gen_truth(g):
    rs = g["reward_schema"]
    lines = [
        "# Golden trajectory",
        "",
        BANNER,
        "",
        "Generated by `solution/recompute.py` from `solution/grounding.yaml`. This file is private. It never enters the agent-visible package and it never enters either ENGRAM projection.",
        "",
        "## Ordered path",
        "",
    ]
    for s in g["truth_steps"]:
        sat = ", ".join(s["satisfies"]) if s["satisfies"] else "none"
        lines.append(f"{s['id']}. {s['action']} Establishes: {s['establishes']} Satisfied checkers: {sat}.")
        lines.append("")
    lines += [
        "## Rejected routes",
        "",
        "Each rejected route names the known-wrong control whose rejection Phase 2 measured. This prose is Bucket N: it may lower a disposition and may never raise one.",
        "",
    ]
    for r in g["rejected_routes"]:
        lines.append(f"- {r['route']} Rejected by control `{r['control']}`.")
    lines += [
        "",
        "## Reward",
        "",
        f"Full reward is exactly {rs['full_reward']} and is reached only at a graded step at or below {rs['target_steps']}, with every gate passing. A graded step of {rs['baseline_steps']} or worse scores 0.0, and any failed gate scores exactly 0.0 regardless of step.",
        "",
        "## What this bundle does not claim",
        "",
        "It does not claim the reference optimizer reaches full reward. That has never been executed, because the authoring host has no accelerator. The novelty half of the reference solution is proven by execution inside a real training loop; the reward half is unproven.",
        "",
    ]
    _w(os.path.join(BUNDLE, "solution", "TRUTH.md"), "\n".join(lines))


def gen_rubrics(g):
    items = []
    for it in g["rubric_items"]:
        items.append(
            {
                "id": it["id"],
                "dimension": it["dimension"],
                "weight": it["weight"],
                "evaluation_target": it["evaluation_target"],
                "criterion": it["criterion"],
                "judgment": it["judgment"],
                "evidence": it["evidence"],
                "mode": it["mode"],
                "reduces_to": it.get("reduces_to"),
                "semantic_residue": it.get("semantic_residue"),
            }
        )
    doc = {
        "_generated_by": "solution/recompute.py",
        "_source_of_truth": "solution/grounding.yaml",
        "_banner": BANNER,
        "compilation_floor": g["compilation_floor"],
        "items": items,
    }
    _w(os.path.join(BUNDLE, "solution", "rubrics.json"), json.dumps(doc, indent=1, sort_keys=True) + "\n")
    return doc


def gen_test_output(g, rubrics):
    compiled = [i for i in rubrics["items"] if i["mode"] == "compiled"]
    lines = [
        f"# {BANNER}",
        "# Generated by solution/recompute.py from solution/grounding.yaml.",
        "# Contains only the implied relation. No criterion prose and no reference text.",
        "import json, os, sys",
        "sys.path.insert(0, os.path.join(os.path.dirname(__file__)))",
        "from checkers import outcomes",
        "",
        "def _o():",
        "    return outcomes.load()",
        "",
    ]
    for it in compiled:
        lines += [
            f"def test_{it['id']}():",
            f"    assert _o()[{it['id']!r}] is True",
            "",
        ]
    _w(os.path.join(BUNDLE, "tests", "test_output.py"), "\n".join(lines))
    return [i["id"] for i in compiled]


def gen_provenance_payload(g):
    payload = {
        "schema": "forge.provenance/v1",
        "banner": BANNER,
        "task_family": g["task_identity"]["family"],
        "archetype": g["task_identity"]["archetype"],
        "upstream_identity": g["task_identity"]["upstream"],
        "upstream_license": "MIT",
        "origin": "derived",
        "source_kind": "public_repository",
        "canonical_repository_identity": "KellerJordan/modded-nanogpt",
        "provenance_date": None,
        "fork_ancestry_snapshot_digest": None,
        "base_commit_sha": None,
        "task_generating_event_timestamp": None,
        "ancestry_attestation_digest": None,
        "ancestry_attestation_signer": None,
        "event_attestation_digest": None,
        "event_attestation_signer": None,
        "attestation_status": "attestation-unavailable",
        "screening_roots": {
            "exclusion_list": None,
            "freeze_date_table": None,
            "near_duplicate_index": None,
            "source_attestation": None,
        },
        "screening_root_status": "unresolvable-all-null",
        "atom_results": {
            "exclusion_matching": "screening-unverified",
            "freeze_holdout": "screening-unverified",
            "near_duplicate_screening": "screening-unverified",
            "sanitization": "executed",
            "empty_submission_validation": "executed",
        },
        "instrument_versions": {
            "novelty": "inrun/v2",
            "extractor": "extract/v1",
            "recompute": "recompute/v1",
        },
        "novelty_corpus": {
            "freeze_date": g["novelty_gate"]["corpus_freeze_date"],
            "members_built": g["novelty_gate"]["corpus_coverage"]["members_built"],
            "members_failed": g["novelty_gate"]["corpus_coverage"]["members_failed"],
            "distinct_behaviours": g["novelty_gate"]["corpus_coverage"]["distinct_behaviours"],
            "records_in_lineage": g["novelty_gate"]["corpus_coverage"]["records_in_lineage"],
            "complete": g["novelty_gate"]["corpus_coverage"]["complete"],
            "capture_scope": g["novelty_gate"]["capture_scope"],
            "divergence_floor": g["novelty_gate"]["novelty_divergence_floor"],
            "floor_status": g["novelty_gate"]["floor_status"],
        },
        "reader_note": (
            "Every value here is a producer claim, never evidence. A reader recomputes each "
            "one from committed bytes and named roots. Assertions here may be contradicted "
            "and must never be relied upon."
        ),
    }
    text = yaml.safe_dump(payload, sort_keys=True, default_flow_style=False)
    _w(os.path.join(BUNDLE, "solution", "provenance.yaml"), text)
    return hashlib.sha256(text.encode()).hexdigest()


def main():
    g = load()
    gen_solve_sh(g)
    gen_truth(g)
    rub = gen_rubrics(g)
    compiled_ids = gen_test_output(g, rub)
    payload_hash = gen_provenance_payload(g)

    compiled_weight = sum(i["weight"] for i in rub["items"] if i["mode"] == "compiled")
    total_weight = sum(i["weight"] for i in rub["items"])
    print(json.dumps({
        "compiled_items": compiled_ids,
        "compiled_weight_share": round(compiled_weight / total_weight, 6),
        "compilation_floor": g["compilation_floor"],
        "floor_met": (compiled_weight / total_weight) >= g["compilation_floor"],
        "provenance_payload_sha256": payload_hash,
    }, indent=1))


if __name__ == "__main__":
    main()
