# GENERATED SECTION. DO NOT HAND-EDIT.
# Generated by solution/recompute.py from solution/grounding.yaml.
# Contains only the implied relation. No criterion prose and no reference text.
import json, os, sys
sys.path.insert(0, os.path.join(os.path.dirname(__file__)))
from checkers import outcomes

def _o():
    return outcomes.load()

def test_frozen_recipe_unchanged():
    assert _o()['frozen_recipe_unchanged'] is True

def test_one_fwd_bwd_per_step():
    assert _o()['one_fwd_bwd_per_step'] is True

def test_multi_seed_noise_floor():
    assert _o()['multi_seed_noise_floor'] is True

def test_faithful_reporting():
    assert _o()['faithful_reporting'] is True

def test_optimizer_not_copied():
    assert _o()['optimizer_not_copied'] is True
