"""Generate the pytest suite that asserts the deterministic half.

WHY GENERATE RATHER THAN HAND-WRITE. A hand-written suite drifts from the registry: someone adds a
concern and forgets the test, or renames a concern and leaves a test asserting an id that no longer
exists. Generating from the registry makes that impossible by construction -- the suite cannot
assert a concern that is not declared, and cannot omit one that is.

WHAT THE GENERATED FILE MAY CONTAIN. Ids and the implied relation, and nothing else. No criterion
prose and no reference text: a test file that quotes the answer key is a test file that leaks it to
anyone who reads the repository, and prose duplicated into a test is prose that goes stale the
moment the registry changes.

TRI-STATE HANDLING. A concern declared `always_measurable=False` may legitimately report
NOT_MEASURED, so its test SKIPS in that case -- visibly, in the pytest report. Every other concern
asserts PASS, so a NOT_MEASURED there is a FAILED assertion rather than a silent absence. Those two
counts differ, and conflating them understates failures.
"""
from __future__ import annotations

import os
import subprocess
import sys
import tempfile
from dataclasses import asdict, dataclass
from typing import Iterable

from .schemas import Concern, Owner

BANNER = "GENERATED BY bia_verifier.pytest_gen. DO NOT HAND-EDIT."


def generate(concerns: Iterable[Concern]) -> str:
    """Emit one parametrized test without interpolating IDs into executable syntax."""
    det = [c for c in concerns if c.owner is Owner.DETERMINISTIC]
    cases = [(c.id, c.always_measurable) for c in sorted(det, key=lambda x: x.id)]

    lines = [
        f"# {BANNER}",
        "#",
        "# Contains ids and the implied relation only -- no criterion prose, no reference text.",
        "# A concern that may legitimately not run SKIPS; every other concern asserts PASS, so a",
        "# not_measured elsewhere is a FAILED assertion and not a silent absence.",
        "import pytest",
        "",
        "from bia_verifier.outcomes import load, state, why",
        f"CASES = {cases!r}",
        "",
        "@pytest.mark.parametrize(('concern_id', 'always_measurable'), CASES)",
        "def test_deterministic_concern(concern_id, always_measurable):",
        "    st = state(concern_id)",
        "    if not always_measurable and st == 'not_measured':",
        "        pytest.skip(why(concern_id))",
        "    assert st == 'pass', why(concern_id)",
    ]
    return "\n".join(lines).rstrip() + "\n"


def write(concerns: Iterable[Concern], path: str) -> str:
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    src = generate(concerns)
    with open(path, "w", newline="\n") as f:
        f.write(src)
    return path


@dataclass
class PytestReport:
    returncode: int
    test_file: str
    junit_xml: str
    stdout: str
    stderr: str

    @property
    def passed(self) -> bool:
        return self.returncode == 0

    def to_dict(self) -> dict:
        return {**asdict(self), "passed": self.passed}


def run(concerns: Iterable[Concern], outcomes_path: str, out_dir: str,
        *, timeout: int = 120) -> PytestReport:
    os.makedirs(out_dir, exist_ok=True)
    test_file = write(concerns, os.path.join(out_dir, "test_verifier_generated.py"))
    junit_xml = os.path.join(out_dir, "pytest.xml")
    env = dict(os.environ)
    env["BIA_VERIFIER_OUTCOMES"] = os.path.abspath(outcomes_path)
    package_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    env["PYTHONPATH"] = os.pathsep.join(
        p for p in (package_root, env.get("PYTHONPATH", "")) if p)
    env["PYTEST_DISABLE_PLUGIN_AUTOLOAD"] = "1"
    with tempfile.TemporaryDirectory(prefix="bia-verifier-pytest-") as cwd:
        try:
            completed = subprocess.run(
                [sys.executable, "-m", "pytest", "-q", "--noconftest", test_file,
                 f"--junitxml={junit_xml}"],
                cwd=cwd, env=env, text=True, capture_output=True, timeout=timeout,
            )
        except subprocess.TimeoutExpired as e:
            stdout = _timeout_text(e.stdout)
            stderr = _timeout_text(e.stderr)
            return PytestReport(124, test_file, junit_xml, stdout[-8000:],
                                (stderr + f"\npytest timed out after {timeout}s")[-8000:])
    return PytestReport(completed.returncode, test_file, junit_xml,
                        completed.stdout[-8000:], completed.stderr[-8000:])


def _timeout_text(value: str | bytes | None) -> str:
    if isinstance(value, bytes):
        return value.decode("utf-8", "replace")
    return value or ""
