#!/usr/bin/env bash
# GENERATED SECTION. DO NOT HAND-EDIT.
# Generated by solution/recompute.py from solution/grounding.yaml.
set -euo pipefail
cd "$(dirname "$0")/.."

# The oracle installs the reference optimizer as the submission and runs the instrumented
# harness runner for the declared seed set. It reaches full reward only if the reference
# optimizer actually attains the target loss inside the bound step count, which has not
# been demonstrated on any host to date. See gap-oracle-unexecuted-no-accelerator.
mkdir -p submission/logs
cp solution/reference_optimizer.py submission/optimizer.py
exec python runner/run_track3.py --seeds 0,1 --max-steps 3500
